In [2]:
import pandas as pd

In [ ]:
path='E:\\sagar\\2 sagar ORDER\\ORDER\\Prgramming\\python\\projects\\stocktracker\\mutual fund data\\sbi'

In [5]:
a=pd.read_excel('E:\\sagar\\2 sagar ORDER\\ORDER\\Prgramming\\python\\projects\\stocktracker\\mutual fund data\\sbi\\2021-January-SBI EQUITY HYBRID FUND PORTFOLIO.xlsx', index_col=0)

In [7]:
a

,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
NaN,NaN,SBI MUTUAL FUND,024,NaN,NaN,NaN,NaN,NaN,Back to Index
NaN,NaN,SCHEME NAME :,SBI Equity Hybrid Fund,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,PORTFOLIO STATEMENT AS ON :,2021-01-31 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,Name of the Instrument / Issuer,ISIN,Rating / Industry^,Quantity,Market value\n(Rs. in Lakhs),% to AUM,YTM %,Notes & Symbols
...,...,...,...,...,...,...,...,...,...
NaN,NaN,1. Non Convertible Debentures and Bonds are c...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,2. ^Industry classification as recommended by ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,3. Security is in default beyond its maturity ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,NaN,Name of Security,ISIN,Value of the security considered under net rec...,Value of the security considered under net rec...,Total amount (Including Principal and Interest...,NaN,NaN,NaN
NaN,NaN,RHFL 08.70% (Series I Cat I & II) 03-Jan-2020,INE217K07AB6,0,0,10870,NaN,NaN,NaN