In [1]:
import pandas as pd
import streamlit as st
#this files import xl file into panda and saves it in modified form

In [2]:
path ='E:\\sagar\\2 sagar ORDER\\ORDER\\Prgramming\\python\\projects\\stocktracker\\mutual fund data\\sbi\\2021-January-SBI EQUITY HYBRID FUND PORTFOLIO.xlsx'

In [3]:
A=pd.read_excel(path)

In [4]:
cols = ['A','B','C','D','E','F','G','H','I','J']
A.columns = cols
print(A.columns)

Index(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'], dtype='object')

In [5]:
A

,A,B,C,D,E,F,G,H,I,J
0,NaN,NaN,SBI MUTUAL FUND,024,NaN,NaN,NaN,NaN,NaN,Back to Index
1,NaN,NaN,SCHEME NAME :,SBI Equity Hybrid Fund,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,PORTFOLIO STATEMENT AS ON :,2021-01-31 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,Name of the Instrument / Issuer,ISIN,Rating / Industry^,Quantity,Market value\n(Rs. in Lakhs),% to AUM,YTM %,Notes & Symbols
...,...,...,...,...,...,...,...,...,...,...
167,NaN,NaN,1. Non Convertible Debentures and Bonds are c...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168,NaN,NaN,2. ^Industry classification as recommended by ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169,NaN,NaN,3. Security is in default beyond its maturity ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170,NaN,NaN,Name of Security,ISIN,Value of the security considered under net rec...,Value of the security considered under net rec...,Total amount (Including Principal and Interest...,NaN,NaN,NaN
171,NaN,NaN,RHFL 08.70% (Series I Cat I & II) 03-Jan-2020,INE217K07AB6,0,0,10870,NaN,NaN,NaN

In [6]:
#B=A.drop([0])

In [7]:
amc_name=A.iloc[0][2]
amc_name

'SBI MUTUAL FUND'

In [8]:
as_on=A.iloc[2][3]
as_on

datetime.datetime(2021, 1, 31, 0, 0)

In [9]:
scheme_name=A.iloc[1][3]
scheme_name

'SBI Equity Hybrid Fund'

In [10]:
b=A.axes
b
#172*9

[RangeIndex(start=0, stop=172, step=1),
 Index(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J'], dtype='object')]

In [11]:
b=A.drop([0,1,2,3],inplace=True)
b

In [12]:
b=A.drop(['A','B'] ,axis=1,inplace=True)
A

,C,D,E,F,G,H,I,J
4,Name of the Instrument / Issuer,ISIN,Rating / Industry^,Quantity,Market value\n(Rs. in Lakhs),% to AUM,YTM %,Notes & Symbols
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,EQUITY & EQUITY RELATED,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,a) Listed/awaiting listing on Stock Exchanges,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,HDFC Bank Ltd.,INE040A01034,Banks,14000000,194670,5.62,NaN,NaN
...,...,...,...,...,...,...,...,...
167,1. Non Convertible Debentures and Bonds are c...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
168,2. ^Industry classification as recommended by ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
169,3. Security is in default beyond its maturity ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
170,Name of Security,ISIN,Value of the security considered under net rec...,Value of the security considered under net rec...,Total amount (Including Principal and Interest...,NaN,NaN,NaN
171,RHFL 08.70% (Series I Cat I & II) 03-Jan-2020,INE217K07AB6,0,0,10870,NaN,NaN,NaN

In [13]:
'''

EQUITY & EQUITY RELATED
a) Listed/awaiting listing on Stock Exchanges
Total
b) Unlisted
c) Foreign Securities and /or overseas ETF
DEBT INSTRUMENTS
b) Privately Placed/Unlisted
c) Securitised Debt Instruments
d) Central Government Securities
e) State Government Securities
MONEY MARKET INSTRUMENTS
a) Commercial Paper
b) Certificate of Deposits
c) Treasury Bills
d) Bills Re- Discounting
OTHERS
a) Mutual Fund Units / Exchange Traded Funds
b) Gold
c) Short Term Deposits
d) Term Deposits Placed as Margins
e) TREPS / Reverse Repo Investments
Other Current Assets / (Liabilities)
DERIVATIVES
Stock Futures
Index Futures
Derivatives Total
3. Security is in default beyond its maturity date :

'''

'\n\nEQUITY & EQUITY RELATED\na) Listed/awaiting listing on Stock Exchanges\nTotal\nb) Unlisted\nc) Foreign Securities and /or overseas ETF\nDEBT INSTRUMENTS\nb) Privately Placed/Unlisted\nc) Securitised Debt Instruments\nd) Central Government Securities\ne) State Government Securities\nMONEY MARKET INSTRUMENTS\na) Commercial Paper\nb) Certificate of Deposits\nc) Treasury Bills\nd) Bills Re- Discounting\nOTHERS\na) Mutual Fund Units / Exchange Traded Funds\nb) Gold\nc) Short Term Deposits\nd) Term Deposits Placed as Margins\ne) TREPS / Reverse Repo Investments\nOther Current Assets / (Liabilities)\nDERIVATIVES\nStock Futures\nIndex Futures\nDerivatives Total\n3. Security is in default beyond its maturity date :\n\n'

In [14]:
s = pd.Series(list('abc'))